
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/book_sharing?characterEncoding=UTF-8
    username: root
    password: Root123456
  http:
    encoding:
      charset: UTF-8
      enabled: true

server:
  tomcat:
    accept-count: 100
    max-threads: 200
    min-spare-threads: 10
    uri-encoding: UTF-8
  port: 9999

mybatis:
  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.zuovx.book.model


  ##jwt 加密私钥
authjwt:
  base64Secret: MDk4ZjZiY2Q0NjIxZDM3M2NhZGU0ZTgzMjYyN2I0ZjY=
  # 过期时间为一天
  TTLtimes: 86400000
